// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class remove_nullable_from_avatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_nullable_from_avatar));
        
        string IMigrationMetadata.Id
        {
            get { return "201501051939174_remove_nullable_from_avatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
